include_guard(GLOBAL)

# Canonical install dirs
include(GNUInstallDirs)

if(NOT WIN32 AND CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
  set(CMAKE_INSTALL_PREFIX "/opt/aether_sdr")
  set(CPACK_PACKAGING_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")
endif()

set(AETHER_PLUGINS_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin/plugins$<1:>")
set(AETHER_INSTALL_PLUGINIR "${CMAKE_INSTALL_BINDIR}/plugins")
